name: laserfarm

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.8
  - pdal
  - python-pdal
  - gdal
  - gcc=12.1.0
  - cxx-compiler
  - libgcc=5.2.0
  - shapely  # needed to install the correct version of geos
  - pip
  - pip:
      - -r requirements.txt
      - .
