name: laserfarm

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.7
  - pdal
  - python-pdal
  - gdal
  - gcc
  - libcxx
  - shapely  # needed to install the correct version of geos
  - pip
  - pip:
      - -r requirements.txt
      - .
